apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
data:
  service.name: {{ include "auth-service.fullname" . }}
  service.version: {{ .Chart.AppVersion | quote }}